# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
#CoE Faculty Senate Charter, preamble/purpose of CoE Faculty Senate, who qualifies as a member
#SEC members and officers
# Resolutions and minutes

main:
  # - name: About
  #   weight: 20
  # - name: About the Senate
  #   url: overview
  #   parent: About
  #   weight: 21
  # - name: Qualify as Members
  #   url: qualify
  #   parent: About
  #   weight: 23
  - name: Members and Officers
    weight: 30
  - name: Members
    url: post/22-02-02-senate-member
    parent: Members and Officers
    weight: 31
  - name: Executive Committee
    url: "#team"
    parent: Members and Officers
    weight: 32
  - name: Docs & Resources
    weight: 40
  - name: Charter
    url: https://drive.google.com/file/d/1NHxJF1I2bkFyWbYwdVwc8ngSr0MIeDmt/view?usp=sharing
    parent: Docs & Resources
    weight: 41
  - name: Minutes
    url: https://drive.google.com/drive/folders/1KMIwfTT-gJF4QTcaICOOdHyfoPsmYxUz?usp=sharing
    parent: Docs & Resources
    weight: 42
  - name: Public Document Archive
    url: https://drive.google.com/drive/folders/1JTnSUy3VrwZAp0mcTCz6CUwZ1er8O6Hp?usp=sharing
    parent: Docs & Resources
    weight: 43
